services:
  db:
    image: 'postgis/postgis:18-3.6'
    container_name: sikboo-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - sikboo-data:/var/lib/postgresql
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - sikboo-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  sikboo-network:
    driver: bridge

volumes:
  sikboo-data:
